title: Allie Cooperman
logo: /images/headshot.jpg
description: PhD student at the University of Minnesota - Twin Cities
page-col: "#9CC8FF"
text-col: "#000000"
link-col: "#000077"
theme: jekyll-theme-minimal